IZVRSNI =  ./zadatak01/a.out ./zadatak02/a.out ./zadatak03/a.out ./zadatak04/a.out ./zadatak05/a.out ./zadatak06/a.out ./zadatak07/a.out ./zadatak08/a.out ./zadatak09/a.out ./zadatak10/a.out ./zadatak11/a.out ./zadatak12/a.out ./zadatak13/a.out ./zadatak14/a.out ./zadatak15/a.out

clean:
	rm -rf $(IZVRSNI)


